const aiTools = [
  {
    name: "ChatGPT Plus",
    provider: "OpenAI",
    category: "chat",
    pricingType: "paid",
    monthlyPrice: 20,
    contextWindow: 128000,
    strengths: ["reasoning", "general-purpose", "coding", "plugins"],
    weaknesses: ["rate-limits", "data-privacy-concerns"],
    bestFor: ["chat", "coding", "analysis", "content-writing"],
    website: "https://chat.openai.com",
    apiAvailable: false,
    openSource: false,
    popularityScore: 98,
    carbonPerRequest: 4.2,
    energyRating: "high",
    ethicalScore: 72,
    dataPrivacy: "moderate",
  },
  {
    name: "ChatGPT Team",
    provider: "OpenAI",
    category: "chat",
    pricingType: "paid",
    monthlyPrice: 30,
    contextWindow: 128000,
    strengths: ["workspace-sharing", "higher-limits", "no-training-on-data"],
    weaknesses: ["expensive-at-scale"],
    bestFor: ["team-collaboration", "shared-prompts", "enterprise-chat"],
    website: "https://chat.openai.com",
    apiAvailable: false,
    openSource: false,
    popularityScore: 85,
    carbonPerRequest: 4.2,
    energyRating: "high",
    ethicalScore: 85,
    dataPrivacy: "strong",
  },
  {
    name: "Claude Pro",
    provider: "Anthropic",
    category: "coding",
    pricingType: "paid",
    monthlyPrice: 20,
    contextWindow: 200000,
    strengths: ["coding", "long-context", "reasoning", "safety"],
    weaknesses: ["slower", "limited-integrations"],
    bestFor: ["coding", "architecture", "large-files", "documentation"],
    website: "https://claude.ai",
    apiAvailable: false,
    openSource: false,
    popularityScore: 92,
    carbonPerRequest: 3.8,
    energyRating: "high",
    ethicalScore: 90,
    dataPrivacy: "strong",
  },
  {
    name: "Claude Team",
    provider: "Anthropic",
    category: "coding",
    pricingType: "paid",
    monthlyPrice: 30,
    contextWindow: 200000,
    strengths: ["team-billing", "admin-controls", "zero-data-retention"],
    weaknesses: ["minimum-5-seats"],
    bestFor: ["engineering-teams", "secure-coding", "R&D"],
    website: "https://claude.ai",
    apiAvailable: false,
    openSource: false,
    popularityScore: 80,
    carbonPerRequest: 3.8,
    energyRating: "high",
    ethicalScore: 95,
    dataPrivacy: "strong",
  },
  {
    name: "Gemini Advanced",
    provider: "Google",
    category: "research",
    pricingType: "paid",
    monthlyPrice: 20,
    contextWindow: 1000000,
    strengths: ["massive-context", "multimodal", "google-workspace-integration"],
    weaknesses: ["inconsistent-coding"],
    bestFor: ["research", "document-analysis", "data-extraction"],
    website: "https://gemini.google.com",
    apiAvailable: false,
    openSource: false,
    popularityScore: 85,
    carbonPerRequest: 2.1,
    energyRating: "medium",
    ethicalScore: 78,
    dataPrivacy: "moderate",
  },
  {
    name: "Perplexity Pro",
    provider: "Perplexity AI",
    category: "research",
    pricingType: "paid",
    monthlyPrice: 20,
    contextWindow: 128000,
    strengths: ["web-search", "citations", "real-time-data", "multiple-models"],
    weaknesses: ["not-for-coding", "no-file-editing"],
    bestFor: ["research", "fact-checking", "market-analysis", "academic"],
    website: "https://perplexity.ai",
    apiAvailable: true,
    openSource: false,
    popularityScore: 88,
    carbonPerRequest: 1.5,
    energyRating: "low",
    ethicalScore: 82,
    dataPrivacy: "strong",
  },
  {
    name: "GitHub Copilot Pro",
    provider: "Microsoft",
    category: "coding",
    pricingType: "paid",
    monthlyPrice: 10,
    contextWindow: 8000,
    strengths: ["code-completion", "IDE-integration", "fast", "inline-suggestions"],
    weaknesses: ["limited-context"],
    bestFor: ["coding", "autocomplete", "boilerplate", "refactoring"],
    website: "https://github.com/features/copilot",
    apiAvailable: false,
    openSource: false,
    popularityScore: 95,
    carbonPerRequest: 0.8,
    energyRating: "low",
    ethicalScore: 75,
    dataPrivacy: "moderate",
  },
  {
    name: "GitHub Copilot Enterprise",
    provider: "Microsoft",
    category: "coding",
    pricingType: "paid",
    monthlyPrice: 39,
    contextWindow: 32000,
    strengths: ["repo-wide-context", "pr-summaries", "security-scanning"],
    weaknesses: ["expensive", "requires-github-enterprise"],
    bestFor: ["enterprise-engineering", "large-codebases", "security-audits"],
    website: "https://github.com/features/copilot",
    apiAvailable: false,
    openSource: false,
    popularityScore: 75,
    carbonPerRequest: 1.2,
    energyRating: "low",
    ethicalScore: 85,
    dataPrivacy: "strong",
  },
  {
    name: "Cursor Pro",
    provider: "Anysphere",
    category: "coding",
    pricingType: "paid",
    monthlyPrice: 20,
    contextWindow: 128000,
    strengths: ["full-IDE", "multi-file-editing", "agent-mode", "fast-apply"],
    weaknesses: ["requires-vs-code-fork"],
    bestFor: ["coding", "refactoring", "full-stack-development"],
    website: "https://cursor.com",
    apiAvailable: false,
    openSource: false,
    popularityScore: 92,
    carbonPerRequest: 3.5,
    energyRating: "high",
    ethicalScore: 80,
    dataPrivacy: "strong",
  },
  {
    name: "Cursor Business",
    provider: "Anysphere",
    category: "coding",
    pricingType: "paid",
    monthlyPrice: 40,
    contextWindow: 200000,
    strengths: ["privacy-mode", "centralized-billing", "team-management"],
    weaknesses: ["expensive"],
    bestFor: ["secure-development", "agency-teams", "enterprise-coding"],
    website: "https://cursor.com",
    apiAvailable: false,
    openSource: false,
    popularityScore: 70,
    carbonPerRequest: 3.5,
    energyRating: "high",
    ethicalScore: 95,
    dataPrivacy: "strong",
  },
  {
    name: "Midjourney Pro",
    provider: "Midjourney",
    category: "image",
    pricingType: "paid",
    monthlyPrice: 60,
    contextWindow: 0,
    strengths: ["stealth-mode", "fast-gpu-time", "concurrent-jobs"],
    weaknesses: ["discord-only", "expensive"],
    bestFor: ["professional-design", "marketing-agencies", "game-assets"],
    website: "https://midjourney.com",
    apiAvailable: false,
    openSource: false,
    popularityScore: 82,
    carbonPerRequest: 8.5,
    energyRating: "very-high",
    ethicalScore: 55,
    dataPrivacy: "weak",
  },
  {
    name: "DALL-E 3 API",
    provider: "OpenAI",
    category: "image",
    pricingType: "api",
    monthlyPrice: 0,
    contextWindow: 0,
    strengths: ["API-access", "text-rendering", "integration-ready"],
    weaknesses: ["pay-per-use", "lower-artistic-quality-than-midjourney"],
    bestFor: ["automated-image-generation", "product-mockups", "app-integrations"],
    website: "https://openai.com/dall-e",
    apiAvailable: true,
    openSource: false,
    popularityScore: 78,
    carbonPerRequest: 7.2,
    energyRating: "very-high",
    ethicalScore: 68,
    dataPrivacy: "moderate",
  },
  {
    name: "Llama 3 70B",
    provider: "Meta",
    category: "chat",
    pricingType: "free",
    monthlyPrice: 0,
    contextWindow: 128000,
    strengths: ["open-source", "self-hostable", "no-data-sharing", "highly-capable"],
    weaknesses: ["requires-infrastructure", "no-hosted-UI"],
    bestFor: ["private-deployment", "fine-tuning", "enterprise-on-prem", "cost-saving"],
    website: "https://llama.meta.com",
    apiAvailable: true,
    openSource: true,
    popularityScore: 85,
    carbonPerRequest: 1.2,
    energyRating: "low",
    ethicalScore: 98,
    dataPrivacy: "strong",
  },
  {
    name: "Mistral Large",
    provider: "Mistral AI",
    category: "coding",
    pricingType: "api",
    monthlyPrice: 0,
    contextWindow: 128000,
    strengths: ["european-privacy", "multilingual", "highly-efficient"],
    weaknesses: ["smaller-ecosystem"],
    bestFor: ["coding", "multilingual-tasks", "gdpr-compliance"],
    website: "https://mistral.ai",
    apiAvailable: true,
    openSource: false,
    popularityScore: 76,
    carbonPerRequest: 0.9,
    energyRating: "low",
    ethicalScore: 95,
    dataPrivacy: "strong",
  },
  {
    name: "Replit Core",
    provider: "Replit",
    category: "agent",
    pricingType: "paid",
    monthlyPrice: 25,
    contextWindow: 128000,
    strengths: ["cloud-IDE", "agent-mode", "instant-hosting", "database-included"],
    weaknesses: ["vendor-lock-in"],
    bestFor: ["prototyping", "full-stack-apps", "deployment", "hackathons"],
    website: "https://replit.com",
    apiAvailable: false,
    openSource: false,
    popularityScore: 84,
    carbonPerRequest: 5.0,
    energyRating: "high",
    ethicalScore: 75,
    dataPrivacy: "moderate",
  },
  {
    name: "Bolt.new Pro",
    provider: "StackBlitz",
    category: "agent",
    pricingType: "paid",
    monthlyPrice: 20,
    contextWindow: 200000,
    strengths: ["frontend-generation", "webcontainers", "instant-preview"],
    weaknesses: ["frontend-focused", "limited-backend-capabilities"],
    bestFor: ["UI-generation", "landing-pages", "react-development"],
    website: "https://bolt.new",
    apiAvailable: false,
    openSource: false,
    popularityScore: 88,
    carbonPerRequest: 3.0,
    energyRating: "medium",
    ethicalScore: 78,
    dataPrivacy: "moderate",
  },
  {
    name: "Devin Standard",
    provider: "Cognition",
    category: "agent",
    pricingType: "paid",
    monthlyPrice: 500,
    contextWindow: 128000,
    strengths: ["autonomous-coding", "end-to-end-execution", "issue-resolution"],
    weaknesses: ["very-expensive", "slow-execution", "waitlist"],
    bestFor: ["autonomous-development", "bug-fixing", "complex-engineering"],
    website: "https://devin.ai",
    apiAvailable: false,
    openSource: false,
    popularityScore: 65,
    carbonPerRequest: 12.0,
    energyRating: "very-high",
    ethicalScore: 65,
    dataPrivacy: "moderate",
  },
  {
    name: "Runway Unlimited",
    provider: "Runway ML",
    category: "video",
    pricingType: "paid",
    monthlyPrice: 76,
    contextWindow: 0,
    strengths: ["unlimited-generation", "video-editing", "gen3-alpha"],
    weaknesses: ["expensive", "learning-curve"],
    bestFor: ["video-generation", "creative-production", "filmmaking"],
    website: "https://runwayml.com",
    apiAvailable: true,
    openSource: false,
    popularityScore: 72,
    carbonPerRequest: 15.0,
    energyRating: "very-high",
    ethicalScore: 60,
    dataPrivacy: "weak",
  },
  {
    name: "Jasper Creator",
    provider: "Jasper AI",
    category: "content",
    pricingType: "paid",
    monthlyPrice: 39,
    contextWindow: 32000,
    strengths: ["marketing-copy", "brand-voice", "templates", "seo-mode"],
    weaknesses: ["expensive", "not-for-coding"],
    bestFor: ["content-marketing", "ad-copy", "social-media"],
    website: "https://jasper.ai",
    apiAvailable: false,
    openSource: false,
    popularityScore: 68,
    carbonPerRequest: 2.0,
    energyRating: "medium",
    ethicalScore: 70,
    dataPrivacy: "moderate",
  },
  {
    name: "Jasper Pro",
    provider: "Jasper AI",
    category: "content",
    pricingType: "paid",
    monthlyPrice: 59,
    contextWindow: 32000,
    strengths: ["team-collaboration", "campaign-management", "api-access"],
    weaknesses: ["very-expensive-for-content"],
    bestFor: ["marketing-teams", "enterprise-content", "agencies"],
    website: "https://jasper.ai",
    apiAvailable: true,
    openSource: false,
    popularityScore: 60,
    carbonPerRequest: 2.0,
    energyRating: "medium",
    ethicalScore: 75,
    dataPrivacy: "strong",
  },
  {
    name: "ElevenLabs",
    provider: "ElevenLabs",
    category: "audio",
    pricingType: "paid",
    monthlyPrice: 22,
    contextWindow: 0,
    strengths: ["voice-cloning", "ultra-realistic-tts", "multilingual", "low-latency"],
    weaknesses: ["strict-content-policy", "expensive-for-long-form"],
    bestFor: ["podcasts", "audiobooks", "game-assets", "voiceovers"],
    website: "https://elevenlabs.io",
    apiAvailable: true,
    openSource: false,
    popularityScore: 92,
    carbonPerRequest: 3.0,
    energyRating: "medium",
    ethicalScore: 65,
    dataPrivacy: "moderate",
  },
  {
    name: "PlayHT",
    provider: "PlayHT",
    category: "audio",
    pricingType: "paid",
    monthlyPrice: 39,
    contextWindow: 0,
    strengths: ["voice-generation", "api-reliability", "bulk-generation"],
    weaknesses: ["UI-can-be-clunky"],
    bestFor: ["automated-youtube-channels", "marketing-videos", "ivr-systems"],
    website: "https://play.ht",
    apiAvailable: true,
    openSource: false,
    popularityScore: 78,
    carbonPerRequest: 2.8,
    energyRating: "medium",
    ethicalScore: 70,
    dataPrivacy: "moderate",
  },
  {
    name: "Gamma",
    provider: "Gamma",
    category: "presentation",
    pricingType: "paid",
    monthlyPrice: 16,
    contextWindow: 0,
    strengths: ["instant-presentations", "beautiful-ui", "web-native", "embeddable"],
    weaknesses: ["limited-export-formats", "rigid-layouts"],
    bestFor: ["pitch-decks", "internal-memos", "quick-presentations"],
    website: "https://gamma.app",
    apiAvailable: false,
    openSource: false,
    popularityScore: 89,
    carbonPerRequest: 1.5,
    energyRating: "low",
    ethicalScore: 85,
    dataPrivacy: "strong",
  },
  {
    name: "Tome",
    provider: "Tome",
    category: "presentation",
    pricingType: "paid",
    monthlyPrice: 16,
    contextWindow: 0,
    strengths: ["ai-storytelling", "dalle-integration", "responsive-design"],
    weaknesses: ["credits-burn-fast"],
    bestFor: ["sales-pitches", "creative-briefs", "portfolios"],
    website: "https://tome.app",
    apiAvailable: false,
    openSource: false,
    popularityScore: 83,
    carbonPerRequest: 2.0,
    energyRating: "medium",
    ethicalScore: 82,
    dataPrivacy: "moderate",
  },
  {
    name: "Sora",
    provider: "OpenAI",
    category: "video",
    pricingType: "paid",
    monthlyPrice: 200,
    contextWindow: 0,
    strengths: ["hyper-realistic-video", "physics-simulation", "long-clips"],
    weaknesses: ["very-expensive", "limited-access", "high-carbon"],
    bestFor: ["b-roll", "commercials", "filmmaking", "simulations"],
    website: "https://openai.com/sora",
    apiAvailable: false,
    openSource: false,
    popularityScore: 96,
    carbonPerRequest: 35.0,
    energyRating: "very-high",
    ethicalScore: 50,
    dataPrivacy: "weak",
  },
  {
    name: "Pika Labs",
    provider: "Pika",
    category: "video",
    pricingType: "paid",
    monthlyPrice: 28,
    contextWindow: 0,
    strengths: ["video-generation", "animation", "lip-sync", "discord-integration"],
    weaknesses: ["short-clips", "watermarks-on-low-tiers"],
    bestFor: ["social-media-videos", "memes", "animations", "marketing"],
    website: "https://pika.art",
    apiAvailable: true,
    openSource: false,
    popularityScore: 84,
    carbonPerRequest: 12.0,
    energyRating: "very-high",
    ethicalScore: 68,
    dataPrivacy: "moderate",
  },
  {
    name: "HeyGen",
    provider: "HeyGen",
    category: "video",
    pricingType: "paid",
    monthlyPrice: 29,
    contextWindow: 0,
    strengths: ["ai-avatars", "perfect-lip-sync", "video-translation", "studio-quality"],
    weaknesses: ["uncanny-valley-risk", "credit-system-expensive"],
    bestFor: ["training-videos", "sales-outreach", "youtube-faceless", "localization"],
    website: "https://heygen.com",
    apiAvailable: true,
    openSource: false,
    popularityScore: 90,
    carbonPerRequest: 8.0,
    energyRating: "high",
    ethicalScore: 60,
    dataPrivacy: "moderate",
  },
  {
    name: "Synthesia",
    provider: "Synthesia",
    category: "video",
    pricingType: "paid",
    monthlyPrice: 22,
    contextWindow: 0,
    strengths: ["enterprise-avatars", "multilingual", "lms-integration"],
    weaknesses: ["rigid-animations", "expensive-for-creators"],
    bestFor: ["corporate-training", "hr-onboarding", "how-to-videos"],
    website: "https://synthesia.io",
    apiAvailable: true,
    openSource: false,
    popularityScore: 85,
    carbonPerRequest: 7.5,
    energyRating: "high",
    ethicalScore: 70,
    dataPrivacy: "strong",
  },
  {
    name: "Suno",
    provider: "Suno AI",
    category: "audio",
    pricingType: "paid",
    monthlyPrice: 10,
    contextWindow: 0,
    strengths: ["full-song-generation", "vocals-and-instruments", "fast", "creative"],
    weaknesses: ["copyright-ambiguity", "audio-artifacts"],
    bestFor: ["jingles", "background-music", "creative-projects", "marketing-audio"],
    website: "https://suno.com",
    apiAvailable: false,
    openSource: false,
    popularityScore: 88,
    carbonPerRequest: 4.5,
    energyRating: "high",
    ethicalScore: 40,
    dataPrivacy: "weak",
  },
  {
    name: "Udio",
    provider: "Udio",
    category: "audio",
    pricingType: "paid",
    monthlyPrice: 10,
    contextWindow: 0,
    strengths: ["high-fidelity-audio", "precise-control", "vocal-clarity"],
    weaknesses: ["slower-generation", "complex-prompting"],
    bestFor: ["music-production", "professional-audio", "soundtracks"],
    website: "https://udio.com",
    apiAvailable: false,
    openSource: false,
    popularityScore: 86,
    carbonPerRequest: 5.0,
    energyRating: "high",
    ethicalScore: 45,
    dataPrivacy: "weak",
  },
  {
    name: "Leonardo AI",
    provider: "Leonardo",
    category: "image",
    pricingType: "paid",
    monthlyPrice: 12,
    contextWindow: 0,
    strengths: ["game-assets", "fine-tuned-models", "canvas-editor", "motion-tools"],
    weaknesses: ["steep-learning-curve"],
    bestFor: ["game-development", "concept-art", "ui-assets", "graphic-design"],
    website: "https://leonardo.ai",
    apiAvailable: true,
    openSource: false,
    popularityScore: 85,
    carbonPerRequest: 6.0,
    energyRating: "high",
    ethicalScore: 65,
    dataPrivacy: "moderate",
  },
  {
    name: "Stable Diffusion 3 API",
    provider: "Stability AI",
    category: "image",
    pricingType: "api",
    monthlyPrice: 0,
    contextWindow: 0,
    strengths: ["open-weights", "uncensored-options", "prompt-adherence", "text-in-image"],
    weaknesses: ["requires-comfyui-knowledge-for-local", "inconsistent-anatomy"],
    bestFor: ["developers", "custom-workflows", "local-generation", "app-integrations"],
    website: "https://stability.ai",
    apiAvailable: true,
    openSource: true,
    popularityScore: 89,
    carbonPerRequest: 4.0,
    energyRating: "high",
    ethicalScore: 85,
    dataPrivacy: "strong",
  },
  {
    name: "Microsoft Security Copilot",
    provider: "Microsoft",
    category: "security",
    pricingType: "paid",
    monthlyPrice: 300,
    contextWindow: 128000,
    strengths: ["threat-intelligence", "incident-response", "intune-integration", "defender-integration"],
    weaknesses: ["extremely-expensive", "microsoft-ecosystem-only"],
    bestFor: ["soc-teams", "threat-hunting", "security-operations"],
    website: "https://security.microsoft.com/copilot",
    apiAvailable: true,
    openSource: false,
    popularityScore: 88,
    carbonPerRequest: 8.5,
    energyRating: "high",
    ethicalScore: 92,
    dataPrivacy: "strong",
  },
  {
    name: "PentestGPT",
    provider: "Gelei Deng",
    category: "security",
    pricingType: "free",
    monthlyPrice: 0,
    contextWindow: 64000,
    strengths: ["vulnerability-scanning", "exploit-generation", "ctf-solving"],
    weaknesses: ["requires-gpt4-api", "academic-tool"],
    bestFor: ["penetration-testing", "red-teaming", "security-audits"],
    website: "https://github.com/GreyDGL/PentestGPT",
    apiAvailable: true,
    openSource: true,
    popularityScore: 75,
    carbonPerRequest: 1.2,
    energyRating: "low",
    ethicalScore: 80,
    dataPrivacy: "strong",
  },
  {
    name: "Snyk DeepCode",
    provider: "Snyk",
    category: "security",
    pricingType: "paid",
    monthlyPrice: 50,
    contextWindow: 0,
    strengths: ["sast", "real-time-scanning", "vulnerability-remediation", "ide-integration"],
    weaknesses: ["false-positives", "expensive-for-large-teams"],
    bestFor: ["devsecops", "ci-cd-pipelines", "secure-coding"],
    website: "https://snyk.io",
    apiAvailable: true,
    openSource: false,
    popularityScore: 90,
    carbonPerRequest: 2.5,
    energyRating: "medium",
    ethicalScore: 95,
    dataPrivacy: "strong",
  },
  {
    name: "Kubiya",
    provider: "Kubiya",
    category: "devops",
    pricingType: "paid",
    monthlyPrice: 99,
    contextWindow: 128000,
    strengths: ["kubernetes-management", "slack-integration", "infrastructure-as-code", "platform-engineering"],
    weaknesses: ["steep-learning-curve", "requires-permissions"],
    bestFor: ["sre-teams", "platform-engineering", "kubernetes-troubleshooting"],
    website: "https://kubiya.ai",
    apiAvailable: true,
    openSource: false,
    popularityScore: 72,
    carbonPerRequest: 4.0,
    energyRating: "medium",
    ethicalScore: 85,
    dataPrivacy: "strong",
  },
  {
    name: "Pulumi AI",
    provider: "Pulumi",
    category: "devops",
    pricingType: "freemium",
    monthlyPrice: 0,
    contextWindow: 64000,
    strengths: ["iac-generation", "cloud-architecture", "multi-cloud"],
    weaknesses: ["hallucinates-cloud-apis-sometimes"],
    bestFor: ["infrastructure-as-code", "cloud-provisioning", "devops-automation"],
    website: "https://pulumi.com/ai",
    apiAvailable: false,
    openSource: false,
    popularityScore: 85,
    carbonPerRequest: 2.5,
    energyRating: "medium",
    ethicalScore: 88,
    dataPrivacy: "moderate",
  },
  {
    name: "K8sGpt",
    provider: "K8sGpt",
    category: "devops",
    pricingType: "free",
    monthlyPrice: 0,
    contextWindow: 32000,
    strengths: ["cluster-scanning", "plain-english-errors", "triage"],
    weaknesses: ["requires-external-api-key"],
    bestFor: ["kubernetes-debugging", "cluster-health", "sre"],
    website: "https://k8sgpt.ai",
    apiAvailable: true,
    openSource: true,
    popularityScore: 80,
    carbonPerRequest: 1.0,
    energyRating: "low",
    ethicalScore: 95,
    dataPrivacy: "strong",
  },
  {
    name: "Julius AI",
    provider: "Julius",
    category: "data",
    pricingType: "paid",
    monthlyPrice: 40,
    contextWindow: 128000,
    strengths: ["data-analysis", "python-execution", "chart-generation", "csv-processing"],
    weaknesses: ["limited-to-data-tasks"],
    bestFor: ["data-science", "business-intelligence", "statistical-analysis"],
    website: "https://julius.ai",
    apiAvailable: false,
    openSource: false,
    popularityScore: 82,
    carbonPerRequest: 3.5,
    energyRating: "high",
    ethicalScore: 80,
    dataPrivacy: "strong",
  },
  {
    name: "Akkio",
    provider: "Akkio",
    category: "data",
    pricingType: "paid",
    monthlyPrice: 49,
    contextWindow: 0,
    strengths: ["predictive-ai", "no-code-machine-learning", "forecasting"],
    weaknesses: ["black-box-models", "expensive"],
    bestFor: ["marketing-agencies", "sales-forecasting", "predictive-analytics"],
    website: "https://akkio.com",
    apiAvailable: true,
    openSource: false,
    popularityScore: 78,
    carbonPerRequest: 5.0,
    energyRating: "high",
    ethicalScore: 75,
    dataPrivacy: "moderate",
  },
  {
    name: "Amazon Q Developer",
    provider: "AWS",
    category: "cloud",
    pricingType: "paid",
    monthlyPrice: 19,
    contextWindow: 128000,
    strengths: ["aws-native", "cloudformation-generation", "iam-policy-generation", "legacy-code-upgrade"],
    weaknesses: ["aws-biased"],
    bestFor: ["aws-engineering", "cloud-migration", "serverless-development"],
    website: "https://aws.amazon.com/q/developer/",
    apiAvailable: false,
    openSource: false,
    popularityScore: 88,
    carbonPerRequest: 1.5,
    energyRating: "low",
    ethicalScore: 90,
    dataPrivacy: "strong",
  },
  {
    name: "AWS Bedrock",
    provider: "AWS",
    category: "cloud",
    pricingType: "api",
    monthlyPrice: 0,
    contextWindow: 200000,
    strengths: ["multiple-foundational-models", "enterprise-security", "vpc-integration"],
    weaknesses: ["complex-setup", "pay-per-token"],
    bestFor: ["enterprise-ai-deployment", "secure-cloud-apps", "rag-architectures"],
    website: "https://aws.amazon.com/bedrock/",
    apiAvailable: true,
    openSource: false,
    popularityScore: 85,
    carbonPerRequest: 2.0,
    energyRating: "medium",
    ethicalScore: 95,
    dataPrivacy: "strong",
  },
  {
    name: "Firefly AI",
    provider: "Firefly",
    category: "cloud",
    pricingType: "paid",
    monthlyPrice: 150,
    contextWindow: 0,
    strengths: ["cloud-asset-management", "drift-detection", "terraform-generation"],
    weaknesses: ["expensive-for-small-teams"],
    bestFor: ["cloud-ops", "infrastructure-as-code", "multi-cloud-governance"],
    website: "https://firefly.ai",
    apiAvailable: true,
    openSource: false,
    popularityScore: 75,
    carbonPerRequest: 3.0,
    energyRating: "medium",
    ethicalScore: 88,
    dataPrivacy: "strong",
  },
  {
    name: "CloudFix",
    provider: "CloudFix",
    category: "cloud",
    pricingType: "paid",
    monthlyPrice: 200,
    contextWindow: 0,
    strengths: ["aws-cost-optimization", "automated-remediation", "finops"],
    weaknesses: ["aws-only"],
    bestFor: ["finops", "cloud-cost-reduction", "aws-management"],
    website: "https://cloudfix.com",
    apiAvailable: false,
    openSource: false,
    popularityScore: 78,
    carbonPerRequest: 2.5,
    energyRating: "medium",
    ethicalScore: 90,
    dataPrivacy: "strong",
  },
  {
    name: "n8n Advanced AI",
    provider: "n8n",
    category: "workflow",
    pricingType: "freemium",
    monthlyPrice: 24,
    contextWindow: 0,
    strengths: ["open-source-workflow", "self-hostable", "langchain-integration", "custom-nodes"],
    weaknesses: ["steep-learning-curve-for-complex-flows"],
    bestFor: ["ai-automation", "data-pipelines", "agentic-workflows", "webhook-handling"],
    website: "https://n8n.io",
    apiAvailable: true,
    openSource: true,
    popularityScore: 92,
    carbonPerRequest: 1.2,
    energyRating: "low",
    ethicalScore: 95,
    dataPrivacy: "strong",
  },
  {
    name: "Zapier Central",
    provider: "Zapier",
    category: "workflow",
    pricingType: "paid",
    monthlyPrice: 40,
    contextWindow: 0,
    strengths: ["6000-integrations", "no-code-bots", "trigger-based-ai"],
    weaknesses: ["expensive-at-scale", "limited-complex-logic"],
    bestFor: ["sales-automation", "crm-routing", "no-code-operations"],
    website: "https://zapier.com/central",
    apiAvailable: true,
    openSource: false,
    popularityScore: 89,
    carbonPerRequest: 2.0,
    energyRating: "medium",
    ethicalScore: 82,
    dataPrivacy: "moderate",
  },
  {
    name: "Make.com AI",
    provider: "Make",
    category: "workflow",
    pricingType: "freemium",
    monthlyPrice: 16,
    contextWindow: 0,
    strengths: ["visual-scenario-builder", "high-customization", "cost-effective"],
    weaknesses: ["error-handling-can-be-complex"],
    bestFor: ["marketing-automation", "data-syncing", "visual-programming"],
    website: "https://make.com",
    apiAvailable: true,
    openSource: false,
    popularityScore: 85,
    carbonPerRequest: 1.5,
    energyRating: "low",
    ethicalScore: 88,
    dataPrivacy: "moderate",
  },
  {
    name: "MindStudio",
    provider: "YouAi",
    category: "workflow",
    pricingType: "paid",
    monthlyPrice: 49,
    contextWindow: 128000,
    strengths: ["model-agnostic", "custom-ai-apps", "enterprise-deployment"],
    weaknesses: ["new-platform"],
    bestFor: ["internal-tool-building", "ai-app-deployment", "prompt-chaining"],
    website: "https://mindstudio.ai",
    apiAvailable: true,
    openSource: false,
    popularityScore: 74,
    carbonPerRequest: 3.5,
    energyRating: "medium",
    ethicalScore: 80,
    dataPrivacy: "moderate",
  },
  {
    name: "GPT-4o Omni",
    provider: "OpenAI",
    category: "chat",
    pricingType: "freemium",
    monthlyPrice: 20,
    contextWindow: 128000,
    strengths: ["real-time-voice", "native-vision", "blazing-fast", "multilingual"],
    weaknesses: ["can-be-lazy-with-code", "privacy-concerns-with-voice"],
    bestFor: ["multimodal-tasks", "real-time-translation", "fast-conversations"],
    website: "https://openai.com/gpt-4o",
    apiAvailable: true,
    openSource: false,
    popularityScore: 99,
    carbonPerRequest: 3.8,
    energyRating: "high",
    ethicalScore: 78,
    dataPrivacy: "moderate",
  },
  {
    name: "Claude 3.5 Sonnet",
    provider: "Anthropic",
    category: "coding",
    pricingType: "freemium",
    monthlyPrice: 20,
    contextWindow: 200000,
    strengths: ["industry-leading-coding", "artifacts-ui", "humorous-and-human-like", "fast"],
    weaknesses: ["strict-refusal-rates"],
    bestFor: ["software-engineering", "react-prototyping", "nuanced-writing"],
    website: "https://claude.ai",
    apiAvailable: true,
    openSource: false,
    popularityScore: 98,
    carbonPerRequest: 2.5,
    energyRating: "medium",
    ethicalScore: 92,
    dataPrivacy: "strong",
  },
  {
    name: "Gemini 1.5 Pro",
    provider: "Google",
    category: "research",
    pricingType: "paid",
    monthlyPrice: 20,
    contextWindow: 2000000,
    strengths: ["2M-context-window", "video-analysis", "book-length-analysis"],
    weaknesses: ["hallucinates-on-short-prompts", "inconsistent-tone"],
    bestFor: ["analyzing-entire-codebases", "hour-long-video-processing", "legal-discovery"],
    website: "https://gemini.google.com",
    apiAvailable: true,
    openSource: false,
    popularityScore: 90,
    carbonPerRequest: 3.0,
    energyRating: "high",
    ethicalScore: 80,
    dataPrivacy: "moderate",
  },
  {
    name: "Llama 3.1 405B",
    provider: "Meta",
    category: "chat",
    pricingType: "free",
    monthlyPrice: 0,
    contextWindow: 128000,
    strengths: ["frontier-level-intelligence", "open-weights", "synthetic-data-generation"],
    weaknesses: ["massive-hardware-requirements-to-host"],
    bestFor: ["enterprise-self-hosting", "model-distillation", "research"],
    website: "https://llama.meta.com",
    apiAvailable: true,
    openSource: true,
    popularityScore: 94,
    carbonPerRequest: 5.0,
    energyRating: "very-high",
    ethicalScore: 95,
    dataPrivacy: "strong",
  },
  {
    name: "Grok 2",
    provider: "xAI",
    category: "chat",
    pricingType: "paid",
    monthlyPrice: 16,
    contextWindow: 128000,
    strengths: ["uncensored", "real-time-twitter-data", "flux-image-generation-built-in"],
    weaknesses: ["unpredictable-safety", "requires-x-premium"],
    bestFor: ["real-time-news", "unfiltered-brainstorming", "meme-generation"],
    website: "https://x.ai",
    apiAvailable: true,
    openSource: false,
    popularityScore: 85,
    carbonPerRequest: 4.5,
    energyRating: "high",
    ethicalScore: 40,
    dataPrivacy: "weak",
  },
  {
    name: "Luma Dream Machine",
    provider: "Luma AI",
    category: "video",
    pricingType: "freemium",
    monthlyPrice: 30,
    contextWindow: 0,
    strengths: ["fast-video-generation", "high-motion-consistency", "free-tier-available"],
    weaknesses: ["morphing-artifacts", "5-second-limit"],
    bestFor: ["b-roll", "social-media-clips", "concept-visualization"],
    website: "https://lumalabs.ai/dream-machine",
    apiAvailable: true,
    openSource: false,
    popularityScore: 88,
    carbonPerRequest: 14.0,
    energyRating: "very-high",
    ethicalScore: 65,
    dataPrivacy: "moderate",
  },
  {
    name: "Kling AI",
    provider: "Kuaishou",
    category: "video",
    pricingType: "freemium",
    monthlyPrice: 20,
    contextWindow: 0,
    strengths: ["sora-level-physics", "10-second-generation", "complex-prompts"],
    weaknesses: ["chinese-phone-number-required-initially", "slow-generation-queue"],
    bestFor: ["hyper-realistic-video", "cinematic-shots", "ai-filmmaking"],
    website: "https://klingai.com",
    apiAvailable: false,
    openSource: false,
    popularityScore: 86,
    carbonPerRequest: 16.0,
    energyRating: "very-high",
    ethicalScore: 50,
    dataPrivacy: "weak",
  },
  {
    name: "Qwen 2.5 Coder",
    provider: "Alibaba",
    category: "coding",
    pricingType: "free",
    monthlyPrice: 0,
    contextWindow: 128000,
    strengths: ["beats-gpt4-in-coding", "open-weights", "highly-efficient"],
    weaknesses: ["less-versatile-outside-coding"],
    bestFor: ["local-code-completion", "agentic-coding", "self-hosted-copilot"],
    website: "https://qwenlm.github.io/",
    apiAvailable: true,
    openSource: true,
    popularityScore: 82,
    carbonPerRequest: 1.2,
    energyRating: "low",
    ethicalScore: 88,
    dataPrivacy: "strong",
  },
  {
    name: "OpenDevin",
    provider: "Open Source",
    category: "agent",
    pricingType: "free",
    monthlyPrice: 0,
    contextWindow: 128000,
    strengths: ["open-source-devin-alternative", "docker-sandboxed", "community-driven"],
    weaknesses: ["requires-heavy-setup", "hallucinates-commands-sometimes"],
    bestFor: ["autonomous-engineering", "hackers", "cost-free-agents"],
    website: "https://github.com/OpenDevin/OpenDevin",
    apiAvailable: false,
    openSource: true,
    popularityScore: 79,
    carbonPerRequest: 2.0,
    energyRating: "medium",
    ethicalScore: 95,
    dataPrivacy: "strong",
  }
];

module.exports = aiTools;
